export function formDataMapToAPI(data){
    return {
        IdEntidad: data["IdEntidad"] ?? "",
        IdTipoPersona: data["IdTipoPersona"] ?? "",
        TipoPersona: data["TipoPersona"] ?? "",
        IdTipoCedula: data["IdTipoCedula"] ?? "",
        TipoCedula: data["TipoCedula"] ?? "",
        Identificacion: data["Identificacion"] ?? "",
        IdSexo: data["IdSexo"] ?? "",
        Sexo: data["Sexo"] ?? "",
        Nombres: data["Nombres"] ?? "",
        Apellido: data["Apellido"] ?? "",
        RazonSocial: data["RazonSocial"] ?? "",
        FechaNacimiento: data["FechaNacimiento"] ?? "",
        Email: data["Email"] ?? "",
        Telefono: data["Telefono"] ?? "",
        Celular: data["Celular"] ?? "",
        CelularII: data["CelularII"] ?? "",
        IdNacionalidad: data["IdNacionalidad"] ?? "",
        Nacionalidad: data["Nacionalidad"] ?? "",
        IdEstadoCivil: data["IdEstadoCivil"] ?? "",
        EstadoCivil: data["EstadoCivil"] ?? "",
        ApellidoCasada: data["ApellidoCasada"] ?? "",
        
        IdPep: data["IdPep"] ?? "",

        IdProfesion: data["IdProfesion"] ?? "",
        Profesion: data["Profesion"] ?? "",
        Ocupacion: data["Ocupacion"] ?? "",
        NombreEmpresaNegocio: data["NombreEmpresaNegocio"] ?? "",
        DireccionEmpresaNegocio: data["DireccionEmpresaNegocio"] ?? "",
        TelefonoEmpresaNegocio: data["TelefonoEmpresaNegocio"] ?? "",
        EmailEmpresa: data["EmailEmpresa"] ?? "",

        IdActividadEconomica: data["IdActividadEconomica"] ?? "",
        ActividadEconomica: data["ActividadEconomica"] ?? "",
        ReprecentanteLegal: data["ReprecentanteLegal"] ?? "",
        IdentificacionReprecentanteLegal: data["IdentificacionReprecentanteLegal"] ?? "",
        
        AvenidaCalle: data["AvenidaCalle"] ?? "",
        Direccion: data["Direccion"] ?? "",
        IdProvincia: data["IdProvincia"] ?? "",
        Provincia: data["Provincia"] ?? "",
        IdDistrito: data["IdDistrito"] ?? "",
        Distrito: data["Distrito"] ?? "",
        IdCorregimiento: data["IdCorregimiento"] ?? "",
        Corregimiento: data["Corregimiento"] ?? "",
        Urbanizacion: data["Urbanizacion"] ?? "",
        IdDireccion: data["IdDireccion"] ?? "",

        IdContactoEnt: data["IdContactoEnt"] ?? "",
        EmailAdicional: data["EmailAdicional"] ?? "",
        IdPaisResidencia: data["IdPaisResidencia"] ?? "",
        CodigoPostal: data["CodigoPostal"] ?? "",

        IdPerfilFinanciero: data["IdPerfilFinanciero"] ?? "",
        ActividadEmpresaNegocio: data["ActividadEmpresaNegocio"] ?? "",
        
        IdReferenciaPersonal: data["IdReferenciaPersonal"] ?? "",
        NombreReferenciaPersonal: data["NombreReferenciaPersonal"] ?? "",
        ActividadReferenciaPersonal: data["ActividadReferenciaPersonal"] ?? "",
        RelacionClienteReferenciaPersonal: data["RelacionClienteReferenciaPersonal"] ?? "",
        TelefonoReferenciaPersonal: data["TelefonoReferenciaPersonal"] ?? "",
        IdReferenciaBancaria: data["IdReferenciaBancaria"] ?? "",
        NombreReferenciaBancaria: data["NombreReferenciaBancaria"] ?? "",
        ActividadReferenciaBancaria: data["ActividadReferenciaBancaria"] ?? "",
        RelacionClienteReferenciaBancaria: data["RelacionClienteReferenciaBancaria"] ?? "",
        TelefonoReferenciaBancaria: data["TelefonoReferenciaBancaria"] ?? "",
        IdReferenciaComercial: data["IdReferenciaComercial"] ?? "",
        NombreReferenciaComercial: data["NombreReferenciaComercial"] ?? "",
        ActividadReferenciaComercial: data["ActividadReferenciaComercial"] ?? "",
        RelacionClienteReferenciaComercial: data["RelacionClienteReferenciaComercial"] ?? "",
        TelefonoReferenciaComercial: data["TelefonoReferenciaComercial"] ?? "",
    }
}